name: Deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 1,8,14,20 * * *

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Cache dependencies Node
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install
        run: npm i
        
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@1.0.15
        with:
          ENDPOINT: https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_Landkreisdaten/FeatureServer/0/query?f=json&where=GEN%20%3D%20%27COBURG%27&outFields=*&returnGeometry=false&outSR=4326
          CONFIGURATION: '{ "method": "GET" }'

      - name: Build Svelte
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
